version: '4'

services:
  web: 
    build: . 
    volumes:
      - ./backend/scripts:/var/www/html
    ports: 
      - 80:80 
  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d 
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tadreeb_sis
      MYSQL_USER: tadreeb_user
      MYSQL_PASSWORD: userpassword
volumes:
  db:
  