
INSERT INTO Internship (
    title,
    company,
    category,
    location,
    short_description,
    full_description,
    requirements,
    features,
    image_url,
    application_link,
    duration,
    semester,
    deadline,
    slug,
    is_verified
) VALUES
(
    'Al Rajhi Bank Co-op Program 2026',
    'Al Rajhi Bank',
    'Banking',
    'Riyadh (Main Branches)',
    'Join Al Rajhi Bank''s Co-op Program and gain hands-on experience.',
    'Join Al Rajhi Bank''s Co-op Program and gain valuable hands-on experience in the banking sector and related fields. Work alongside industry professionals.',
    JSON_ARRAY('Saudi nationality', 'Bachelor''s student', 'Minimum GPA 2.75/4', 'Pass initial selection and interview'),
    JSON_ARRAY('Saudi nationality', 'Bachelor''s student', 'Minimum GPA 2.75/4', 'Co-op is a mandatory graduation requirement'),
    '/images/blog/alrajhibank.png',
    'https://careers.alrajhibank.com.sa/en/saudi-arabia/jobs/coop-training-%D8%A7%D9%84%D8%AA%D8%AF%D8%B1%D9%8A%D8%A8-%D8%A7%D9%84%D8%AA%D8%B9%D8%A7%D9%88%D9%86%D9%8A-1100037814/',
    '4-6 months',
    JSON_ARRAY('Fall 2025'),
    '2025-12-31',
    'al-rajhi-bank-coop-2026',
    TRUE
),
(
    'PwC Consulting Co-op Program 2026',
    'PwC',
    'Consulting',
    'Riyadh',
    'PwC is seeking driven students for their 2026 Consulting Co-op Program.',
    'Gain hands-on experience in consulting projects across industries.',
    JSON_ARRAY('Saudi nationality', 'Bachelor''s student', 'Minimum GPA 2.75/4'),
    JSON_ARRAY('Consulting projects', 'Mentorship'),
    '/images/blog/PwC.png',
    'https://www.pwc.com/sa/en/careers',
    '4-6 months',
    JSON_ARRAY('Spring 2026'),
    '2026-01-31',
    'pwc-consulting-coop-2026',
    TRUE
),
(
    'STC Co-op Program January 2026',
    'STC',
    'Telecom',
    'Riyadh',
    'Work on digital transformation projects with STC.',
    'Join STC''s Co-op Program and work on real digital transformation projects in areas like software engineering, networks, cybersecurity, data, and business innovation.',
    JSON_ARRAY('Saudi nationality', 'Bachelor''s student', 'Minimum GPA 2.75/4'),
    JSON_ARRAY('Digital projects', 'Mentorship', 'Networking'),
    '/images/blog/STC.png',
    'https://www.stc.com.sa/en/careers',
    '4-6 months',
    'Spring 2026',
    '2026-01-15',
    'stc-coop-january-2026',
    TRUE
),
(
    'Saudi Aramco Co-op Training Program',
    'Saudi Aramco',
    'Oil & Gas',
    'Dhahran, Yanbu, Riyadh',
    'Gain hands-on experience in the world's leading integrated energy company.',
    'Aramco offers high-caliber Saudi university students internship opportunities to gain practical experience and meet graduation requirements in engineering, IT, finance, and other fields.',
    JSON_ARRAY('Saudi nationality', 'Currently enrolled in an in-Kingdom or out-of-Kingdom university', 'Minimum GPA 2.5/4 or equivalent', 'Co-op is a mandatory graduation requirement'),
    JSON_ARRAY('Competitive stipend', 'Professional development', 'Potential pathway to full-time employment'),
    '/images/blog/aramco.png',
    'https://www.aramco.com/en/careers/for-saudi-applicants/student-opportunities/university-and-vocational-college-internship-programs',
    '4-7 months',
    'Spring 2026',
    '2025-12-30',
    'saudi-aramco-coop-spring-2026',
    TRUE
),
(
    'SABIC Cooperative Training Program 2026',
    'SABIC',
    'Petrochemicals',
    'Riyadh, Jubail, Yanbu',
    'Apply academic knowledge in a real business environment in the chemical industry.',
    'SABIC’s Cooperative Training Program is designed for final-year students nominated by their universities. Interns work on business challenges in manufacturing, engineering, supply chain, and corporate functions.',
    JSON_ARRAY('Saudi nationality', 'Final-year student nominated by university', 'Minimum cumulative GPA 2.5/4 or 3.5/5', 'Medically fit'),
    JSON_ARRAY('Stipend and benefits', 'On-site experience', 'Mentorship in a global environment'),
    '/images/blog/sabic.png',
    'https://www.sabic.com/en/careers/middle-east-africa/students-and-fresh-graduates',
    '4-6 months',
    'Spring 2026',
    '2026-01-10',
    'sabic-coop-training-2026',
    TRUE
),
(
    'KPMG COOP and Internship Programs',
    'KPMG',
    'Audit & Advisory',
    'Riyadh, Jeddah, Al Khobar',
    'Gain valuable experience in audit, tax, and advisory services with a Big Four firm.',
    'KPMG’s COOP and Internship Programs are open for senior students from all subject areas. The program provides practical work experience and a potential pathway to the Graduate Development Program.',
    JSON_ARRAY('Senior university student', 'Completing a degree in business, finance, accounting, or IT', 'Strong academic record', 'Eagerness to learn'),
    JSON_ARRAY('Exposure to consulting projects', 'Professional development', 'Work with industry leaders'),
    '/images/blog/kpmg.png',
    'https://kpmg.com/sa/en/careers/coop-and-internship-programs.html',
    '4-6 months',
    JSON_ARRAY('Fall 2025', 'Spring 2026'),
    '2026-01-31',
    'kpmg-coop-internship-2026',
    TRUE
);