USE tadreeb_sis;

INSERT INTO Internship (
    title,
    company,
    category,
    location,
    short_description,
    full_description,
    requirements,
    features,
    image_url,
    application_link,
    duration,
    semester,
    deadline,
    slug,
    is_verified
) VALUES
(
    'Al Rajhi Bank Co-op Program 2026',
    'Al Rajhi Bank',
    'Banking',
    'Riyadh (Main Branches)',
    'Join Al Rajhi Bank''s Co-op Program and gain hands-on experience.',
    'Join Al Rajhi Bank''s Co-op Program and gain valuable hands-on experience in the banking sector and related fields. Work alongside industry professionals.',
    JSON_ARRAY('Saudi nationality', 'Bachelor''s student', 'Minimum GPA 2.75/4', 'Pass initial selection and interview'),
    JSON_ARRAY('Hands-on experience', 'Networking opportunities', 'Professional mentorship'),
    '/images/blog/alrajhibank.png',
    'https://careers.alrajhibank.com.sa/en/saudi-arabia/jobs/coop-training-%D8%A7%D9%84%D8%AA%D8%AF%D8%B1%D9%8A%D8%A8-%D8%A7%D9%84%D8%AA%D8%B9%D8%A7%D9%88%D9%86%D9%8A-1100037814/',
    'Varies per semester',
    'Fall 2025',
    '2025-12-31',
    'al-rajhi-bank-coop-2026',
    FALSE
),
(
    'PwC Consulting Co-op Program 2026',
    'PwC',
    'Consulting',
    'Riyadh',
    'PwC is seeking driven students for their 2026 Consulting Co-op Program.',
    'Gain hands-on experience in consulting projects across industries.',
    JSON_ARRAY('Saudi nationality', 'Bachelor''s student', 'Minimum GPA 2.75/4'),
    JSON_ARRAY('Consulting projects', 'Mentorship'),
    '/images/blog/PwC.png',
    'https://www.pwc.com/sa/en/careers',
    'Varies per semester',
    'Spring 2026',
    '2026-01-31',
    'pwc-consulting-coop-2026',
    FALSE
),
(
    'STC Co-op Program January 2026',
    'STC',
    'Telecom',
    'Riyadh',
    'Work on digital transformation projects with STC.',
    'Join STC''s Co-op Program and work on real digital transformation projects in areas like software engineering, networks, cybersecurity, data, and business innovation.',
    JSON_ARRAY('Saudi nationality', 'Bachelor''s student', 'Minimum GPA 2.75/4'),
    JSON_ARRAY('Digital projects', 'Mentorship', 'Networking'),
    '/images/blog/STC.png',
    'https://www.stc.com.sa/en/careers',
    'Varies per semester',
    'Spring 2026',
    '2026-01-15',
    'stc-coop-january-2026',
    FALSE
);
